app_get_api:
    path: /api
    defaults: { _controller: AppBundle:Default:api }

app_get_device:
    path:     /{device}
    defaults: { _controller: AppBundle:Default:get }
    methods: [GET]

app_manipulate_device:
    path:     /{device}
    defaults: { _controller: AppBundle:Default:patch }
    methods: [PATCH]
